sudo: required
dist: bionic
language: python
cache: pip

python:
  - '3.6'
  - '3.7'
  - '3.8'

env:
  - PIP="pandas<1"
  - PIP="pandas>=1.0.3"
  - PIP="swifter"
  - PIP="pandarallel"

before_install:
  - python -m pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
  - pip install "PIP"

install:
  - check-manifest
  - python setup.py sdist bdist_wheel
  - twine check dist/*
  - pip install -e .

script:
#  - pytest --cov=. tests/
  - pytest --mypy --black tests/
  - pytest --black -m black src/

#after_success:
#  - codecov -F $TEST
